# Site settings
author: Javier Aguilar
title: 
header-img: img/home-bg.png
email: coyote176@msn.com
copyright_name: Javier Aguilar
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  coyote176-10-12

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
